export {default as Home} from './Home'
export {default as MyNav} from './MyNav'
export {default as Contact} from './Contact'
export {default as Service} from './Service'
export {default as About} from './About'
export {default as Help} from './Help'
export {default as Footer} from './Footer'
export {default as Togglebutton} from './Togglebutton'